### ISSUE TITLE
No difference between greedy and non-greedy regexes

### ISSUE THREAD

**Issue by ilanbiala** [klorenz/atom-regex-railroad-diagrams#23]
Ideally the diagram should be different if there is a `/g` at the end instead of `/`, because it means that the regex picks up all instances, and not just the first one.

**Comment by ilanbiala** [comment]
@klorenz is anything in the works for this?

**Comment by klorenz** [comment]
Hi,

there are two issues:  
- greedy vs. non-greedy
- global vs. non-global

there is no work on this right now.  How could it look like? any suggestions?

**Comment by ilanbiala** [comment]
Just put something like (global) or (greedy) somewhere at the end, or at least list the flags to start and see what people suggest.

**Comment by hayes** [comment]
greedy could be implemented the same way a repeat {n1,n2} is implemented, where it shows `greedy` rather than `n1 to n2 times` as text in the back track loop (not sure what to call it). 

Not sure about flags, maybe a vertical list to the left or right of the diagram?

I mostly care about the greedy thing because that is interesting.
Also could we make non-capturing groups have a dashed border (or something) I could open a separate issue.
