### ISSUE TITLE
Feature Request: Ability to trigger manually with selection

### ISSUE THREAD

**Issue by dflock** [klorenz/atom-regex-railroad-diagrams#90]
As mentioned in various issues (#74, #70), this only works if you're regex is recognised as such by atom and is assigned a regex scope. If you have a regex in a string, then it won't be recognised:

```sh
need[java_jdk]='^1\.(7|8)'
```

So, ideally, you could select the regex text, then manually trigger the diagram.

**Comment by mikesprague** [comment]
@dflock I won't speak for @klorenz but my understanding is that he's pretty tied up with "real life" right now and without time to work on this package (it hasn't been actively developed in some time). 

I was added as a contributor because I had previously forked a copy and published it to address some changes in the Atom API. 

What I'm getting at here is that pull requests are welcome - and will be evaluated and merged when appropriate - but it's probably not realistic to expect movement on this anytime soon otherwise.

Feel free to submit a pull request if you want to take a stab at your requested feature. I've also added the help wanted label in case anyone else is looking to contribute. Cheers!

**Comment by klorenz** [comment]
@dflock, many thanks for this idea.  I have implemented a selection and a little editor for regexes, which then can overwrite the selection or be inserted into text.

**Comment by mikesprague** [comment]
Nice to see the updates, welcome back @klorenz!

**Comment by dflock** [comment]
Awesome, thanks!
